# Generated by Django 5.1.1 on 2024-09-27 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
            ],
        ),
        migrations.CreateModel(
            name='FactsCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название факта')),
                ('text', models.TextField(verbose_name='Описание факта')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('title', models.CharField(max_length=128, verbose_name='Служба')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок новости')),
                ('content', models.TextField(verbose_name='Содержание новости')),
                ('publication_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('author', models.CharField(max_length=100, verbose_name='Автор новости')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='PositionManagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=256, verbose_name='Должность')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('date_start', models.DateField(verbose_name='Дата начала работы')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата конца работы')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='CityManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=256, verbose_name='ФИО управляющего')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city', verbose_name='Город')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.positionmanagers', verbose_name='Должность')),
            ],
        ),
    ]
